UHF-9380: Simplified npm audit action.

diff --git a/.github/workflows/npm-audit.yml b/.github/workflows/npm-audit.yml
--- a/.github/workflows/npm-audit.yml
+++ b/.github/workflows/npm-audit.yml
@@ -13,7 +13,8 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
 
-      - name: Set up Node.js, install dependencies
+      - name: Use Node.js from .nvmrc
+        id: npm_audit
         run: |
           node_version=$(cat .nvmrc)
           echo "Using Node.js version $node_version"
@@ -21,28 +22,17 @@ jobs:
           nvm install $node_version
           nvm use $node_version
           npm install --silent
-
-      - name: Check for vulnerabilities
-        id: npm_audit
-        run: |
           set +e
           npm audit --package-lock-only --loglevel=error;
-          
-          # The npm audit command will exit with a 0 exit code if no vulnerabilities were found.
-          if [ $? -eq 0 ]; then echo "CREATE_PR=false" >> $GITHUB_OUTPUT; else echo "CREATE_PR=true" >> $GITHUB_OUTPUT; fi;
-          set -e
-
-      - name: Run npm audit fix
-        id: npm_audit_fix
-        if: steps.npm_audit.outputs.CREATE_PR == 'true'
-        run: |
-          set +e
-          npm audit fix --package-lock-only --loglevel=error;
-          
           # The npm audit command will exit with a 0 exit code if no vulnerabilities were found.
           if [ $? -gt 0 ]; then
-            echo "BC_BREAK=:exclamation: NPM Audit fix couldn't fix all vulnerabilities. Fix them manually by running \`npm audit fix --force\` and test the functionalities thoroughly as there might be breaking changes. :exclamation:" >> $GITHUB_OUTPUT;
+            npm audit fix --package-lock-only --loglevel=error;
+            if [ $? -gt 0 ]; then
+              echo "BC_BREAK=:exclamation: NPM Audit fix could not fix all vulnerabilities. Fix them manually by running \`npm audit fix --force\` and test the functionalities thoroughly as there might be breaking changes. :exclamation:" >> $GITHUB_ENV;
+            fi;
+            echo "CREATE_PR=true" >> $GITHUB_OUTPUT;
           fi;
+          set -e
 
       - name: Create Pull Request
         if: steps.npm_audit.outputs.CREATE_PR == 'true'
@@ -56,7 +46,7 @@ jobs:
           body: |
             # Npm audit
             
-            ${{ steps.npm_audit_fix.outputs.BC_BREAK }}
+            ${{ env.BC_BREAK }}
 
             ## How to install
   
