UHF-9380: Debugging...

diff --git a/.github/workflows/npm-audit.yml b/.github/workflows/npm-audit.yml
--- a/.github/workflows/npm-audit.yml
+++ b/.github/workflows/npm-audit.yml
@@ -45,8 +45,9 @@ jobs:
           npm audit fix --package-lock-only --loglevel=error;
           
           # The npm audit command will exit with a 0 exit code if no vulnerabilities were found.
-          if [ $? -gt 0 ]; then echo "BC_BREAK=:exclamation: NPM Audit fix couldn't fix all vulnerabilities. Fix them manually by running `npm audit fix --force` and test the functionalities thoroughly as there might be breaking changes. :exclamation:" >> $GITHUB_OUTPUT; fi;
-          set -e
+          if [ $? -gt 0 ]; then
+            echo "BC_BREAK=:exclamation: NPM Audit fix couldn't fix all vulnerabilities. Fix them manually by running \`npm audit fix --force\` and test the functionalities thoroughly as there might be breaking changes. :exclamation:" >> $GITHUB_OUTPUT;
+          fi;
 
       - name: Create Pull Request
         if: steps.npm_audit.outputs.CREATE_PR == 'true'
