UHF-8762: Exit codes, comment with report url

diff --git a/.github/workflows/visual.yml b/.github/workflows/visual.yml
--- a/.github/workflows/visual.yml
+++ b/.github/workflows/visual.yml
@@ -86,7 +86,8 @@ jobs:
         working-directory: ${{ env.THEME_FOLDER }}
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          GENERATE_REFERENCES: 1
+          # Uncomment this to force update reference images.
+          #GENERATE_REFERENCES: 1
         run: |
           gh run download -n bitmaps -D backstop_data/full/bitmaps_reference || true
 
@@ -109,7 +110,35 @@ jobs:
 
       - name: Run tests
         working-directory: ${{ env.THEME_FOLDER }}
-        run: npm run full-test
+        if: github.ref != 'refs/heads/main'
+        run: |
+          REPORT_URL="https://city-of-helsinki.github.io/drupal-hdbt/pull/${{ github.event.pull_request.number }}/html_report/"
+          if ! npm run full-test; then
+            echo COMMENT="Tests failed. You can check the results here: $REPORT_URL" >> $GITHUB_ACTIONS
+          else
+            echo COMMENT="Tests passed. You can check the results here: $REPORT_URL" >> $GITHUB_ACTIONS
+          fi
+
+      - name: Find Comment
+        uses: peter-evans/find-comment@v3
+        id: fc
+        with:
+          issue-number: ${{ github.event.pull_request.number }}
+          comment-author: 'github-actions[bot]'
+
+      - name: Create comment
+        if: steps.fc.outputs.comment-id == ''
+        uses: peter-evans/create-or-update-comment@v4
+        with:
+          issue-number: ${{ github.event.pull_request.number }}
+          body: ${{ env.COMMENT }}
+
+      - name: Update comment
+        if: steps.fc.outputs.comment-id != ''
+        uses: peter-evans/create-or-update-comment@v4
+        with:
+          comment-id: ${{ steps.fc.outputs.comment-id }}
+          body: ${{ env.COMMENT }}
 
       - name: Export container logs
         working-directory: ${{ env.DRUPAL_ROOT }}
